services:
  backend:
    image: webrust
    build: .
    restart: unless-stopped
    volumes:
      - ./db:/app/db:rw
    environment:
      - RUST_LOG="tower_http=debug,axum=debug,sqlx=info,info"

  frontend:
    image: webrust-frontend
    build: frontend
    restart: unless-stopped

  caddy:
    image: caddy:2.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - BIND_URL="localhost:80"
      - API_URL="backend:3000"
      - FRONTEND_URL="frontend:3000"

volumes:
  caddy_data:
  caddy_config: