[package]
name = "killer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
nix = { version = "0.30.1", features = ["process"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
signal-hook = "0.3.18"
rand = "0.9.1"
